# netlify.toml

[build]
  # Base directory: directory where the build command is run
  base = "hyperstack-vm-manager/"
  
  # Build command: how to build the React app
  command = "npm install && npm run build"
  
  # Publish directory: directory containing the built static assets
  publish = "hyperstack-vm-manager/build/"
  
  # Functions directory: where Netlify functions live
  functions = "netlify/functions/"

# Redirect rule for the API proxy function
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Optional: Redirect rule if you want the root of your Netlify site
# (e.g., your-site-name.netlify.app) to directly show the VM manager.
# Remove or comment this out if you want other content at the root.
# [[redirects]]
#  from = "/"
#  to = "/index.html"
#  status = 200 