# netlify.toml

[build]
  # NO base directory specified. All paths below are relative to the root.
  
  # Build command: cd into the directory, install, and build
  command = "cd hyperstack-vm-manager && npm install && npm run build"
  
  # Publish directory: relative to the repository root
  publish = "hyperstack-vm-manager/build/"
  
  # Functions directory: relative to the repository root
  functions = "netlify/functions/"

# Redirect rule for the API proxy function
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Optional: Redirect rule if you want the root of your Netlify site
# (e.g., your-site-name.netlify.app) to directly show the VM manager.
# Remove or comment this out if you want other content at the root.
# [[redirects]]
#  from = "/"
#  to = "/index.html"
#  status = 200 