name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # Or your main branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1 # Use the official Ruby setup action
        with:
          ruby-version: '3.1' # Specify the desired Ruby version
          bundler-cache: true # Cache gems to speed up builds

      - name: Build with Jekyll
        run: |
          bundle install
          bundle exec jekyll build -d ./_site

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          # Optional: Set a custom CNAME file if needed
          # cname: yourcustomdomain.com
