name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # Or your default branch name (e.g., main)

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and Deploy
        uses: jekyll/builder@v1
        env:
          JEKYLL_ENV: production
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
